[package]
name = "cosmos-universe"
version = "1.0.0-rc2"
edition = "2021"
publish = false

[lib]
crate-type = ['rlib']

[dependencies]
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
